
# Methods


## A brief review of joint label fusion




## Joint intensity fusion









## ITK implementation

Similar to the other ANTs programs, the software encapsulating
the methods discussed in this work are built upon the Insight Toolkit
(ITK) and conform to ITK coding standards.  In this section we describe the implementation
and usage interface.  The program ``antsJointFusion.cxx`` uses an intuitive
command line interface developed specifically for the ANTs toolkit.  
See Listing 1 for the short help menu available
at the command line.  A more comprehensive long help menu can be produced
(not shown).  The latter provides references and documentation concerning
parameter options.  ``antsJointFusion.cxx`` is the interface for the underlying
ITK-style class:

* ``itkWeightedVotingFusionImageFilter.h``
* ``itkWeightedVotingFusionImageFilter.hxx``

\begin{lstlisting}
COMMAND:
     antsJointFusion

OPTIONS:
     -d, --image-dimensionality 2/3/4
     -t, --target-image targetImage
                        [targetImageModality0,...,targetImageModalityN]
     -g, --atlas-image atlasImage
                       [atlasImageModality0,...,atlasImageModalityN]
     -l, --atlas-segmentation atlasSegmentation
     -a, --alpha 0.1
     -b, --beta 2.0
     -c, --constrain-nonnegative (0)/1
     -p, --patch-radius 2
                        2x2x2
     -m, --patch-metric (PC)/MSQ
     -s, --search-radius 3
                         3x3x3
                         searchRadiusMap.nii.gz
     -e, --exclusion-image label[exclusionImage]
     -x, --mask-image maskImageFilename
     -o, --output labelFusionImage
                  intensityFusionImageFileNameFormat
                  [labelFusionImage,intensityFusionImageFileNameFormat,
                              <labelPosteriorProbabilityImageFileNameFormat>,
                              <atlasVotingWeightImageFileNameFormat>]
     --version
     -v, --verbose (0)/1
     -h
     --help
\end{lstlisting}

``antsJointFusion`` has a number of available parameters (see Listing 1) permitting
operation on 2-, 3- or 4-dimensional data.  The default input parameters and
corresponding definitions are given below:

__Target image set.__  This input (or set of inputs) comprises the image set to be
matched by the input atlases.  If more than one target image is specified, it is
assumed that all modalities are spatially normalized.    If JIF is to be performed
then all target modalities are inferred with only the first image being used for
atlas weighting.  For example, suppose the set of input atlases consists of $N$
modality images per atlas.  Only the first image needs to be specified for the set
of target input images although all $N$ target modalities will be estimated
using JIF.

__Atlas images.__ Each atlas set specified by the ``-g`` option consists of one or
more modality.  It is assumed that these atlases have already been normalized to the
target image.  The ordering of the modalities for each atlas is assumed to match the
ordering specified for the target image and the other atlases.

__Atlas labels.__ When performing JLF, a set of atlas labels is provided with
each atlas set.  Pairing of each atlas label, ``-l`` option,  with each atlas,
``-g`` is assumed from the order of appearance on the command line.   Note that
specification of the atlas labels is optional for performing JIF.

__Alpha.__  The damping parameter ``Alpha`` is the constant value added to
the diagonal elements of the weight(???) matrix (see Equation ()) to prevent the
possible inversion of a singular matrix.  The larger the value, the greater the
stability for matrix inversion but the further away from the true solution. The
default value is 0.1.

__Beta.__  

__Constrain non-negative.__  As described previously, least squares estimation
is required for solving the atlas weights at each voxel.  The
default method for matrix decomposition is Cholesky given its speed.[^1]
However, such a choice could potentially produce negative weights which is
unintuitive.  This led us to include a non-negative least squares solution
option [@lawson] to ensure non-negative weights.

__Patch metric.__ To determine the weights at a current voxel in the target image,
a neighborhood patch centered at the current voxel is compared with neighboring patches in
each atlas.  The similarity between the target and atlas neighborhood patches
can be calculated using a variety of intensity similarity metrics.  Contributions
from additional modality images are simply concatenated into the similarity metric
calculation.  The original JLF work employed Pearson's correlation
[@Wang:2013ab;@Wang:2013aa] which works very well.  Future work includes the
possible inclusion of other patch-based metrics (e.g., mean squares [@Manjon:2010ab]).

[^1]:  Although other techniques, such as QR and singular value decomposition, are more stable,
a sufficiently large ``Alpha`` value ensures non-singularity.  However, if the
condition number is too small, SVD is used.
